### ISSUE TITLE
HA Firewalls

### ISSUE THREAD

**Issue by jordaj2** [o5edaxi/paloversion#1]
Does this script support Palo Alto Firewalls in an HA pair to where it can upgrade both units unattended?

**Comment by o5edaxi** [comment]
The script does not support HA upgrades with controlled failovers. It will upgrade all the firewalls you target simultaneously as quickly as possible, which will cause downtime. It is not intended for a production environment because there is no one-size-fits-all for that.

You can write your own wrapper script which launches this script for each step and manages the failovers, but it is not trivial to determine whether an upgrade step + failover has been successful or not. It requires knowledge of the environment, external tests, engaging application owners, etc., to judge accurately.
