### ISSUE TITLE
Optimize evaluation phase after rebooot

### ISSUE THREAD

**Issue by askthewood** [o5edaxi/paloversion#3]
Hi, 
If Script is rebooting a out of the box Firewall after uploading/installing Firmware, Script has to wait more than 15 Minutes that is able to login back into PA. I can see that the script is not able to login, even if it is using correct PW (due to missing cookie?)
After "Firewall API call response empty or timed out after 3600 seconds." Script is able to login again and change Password, but after that it is not able to login again:
`curl -k -s -6 --interface ens33 -u admin:Admin123--max-time 1800 --connect-timeout 3 '' '' 'https://[fe80::8e36:7aff:fe03:be8]/api/?type=keygen&user=admin&password=admin'` instead of
`curl -k -s -6 --interface ens33 -u admin:Admin123--max-time 1800 --connect-timeout 3 '' '' 'https://[fe80::8e36:7aff:fe03:be8]/api/?type=keygen&user=admin&password=Admin123'`  
till the next timeout "Firewall API call response empty or timed out after 10 seconds."
[023101032058.log](https://github.com/o5edaxi/paloversion/files/13818418/023101032058.log)
[fe80::8e36:7aff:fe03:be8.log](https://github.com/o5edaxi/paloversion/files/13818426/fe80.8e36.7aff.fe03.be8.log)
[PaloVersionBatch.log](https://github.com/o5edaxi/paloversion/files/13818427/PaloVersionBatch.log)

**Comment by o5edaxi** [comment]
Hi,

this is caused by a combination of 2 things:

1. The firewall gives "Invalid Credentials" via API (just like happens via SSH and HTTPS) when authd isn't up yet, so the script has to retry for some time even if that happens because it doesn't 100% indicate an incorrect password.
2. Since 10.2 you get "Please change your password" only when using the keygen API call, and not when using any other API call with HTTP basic auth. Every other API call gives "Invalid Credentials" even if you are using the correct expired password in basic auth.

So the script was attempting "show system info" in a loop waiting for the fw to come up, then the loop times out and the script tried the keygen and changed password. But you had to wait for the timeout. Now I added a keygen check directly during the waiting loop, so it quits faster. Try the latest code and let me know.

**Comment by askthewood** [comment]
Hi, script is now working very smooth and without any issues anymore. 
I've successfully downgraded from 11.1 to 10.1.4 and upgraded again to 11.1.1.
Thank you 👍

**Comment by o5edaxi** [comment]
Excellent!
